# Generated by Django 5.0.1 on 2024-03-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_ticket_user_ticket_passenger"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_amount", models.PositiveIntegerField()),
            ],
        ),
    ]
