# Generated by Django 5.0.1 on 2024-03-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_ticket_luggage_ticket_lunch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
