services:
  app:
    build: .
    user: ${CURRENT_UID}
    container_name: air_ticket
    restart: always
    ports:
      - "127.0.0.1:9080:8000"
    volumes:
      - ./air_ticket:/app
    env_file:
      - .env.docker
    command: [
      "sh", "-c", "python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py loaddata fixtures/*.json &&
      python manage.py runserver 0.0.0.0:8000"
    ]
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16.2
    container_name: postgres_air_ticket
    restart: always
    env_file:
      - .env.docker_db
    environment:
      - DB_HOST=postgres_air_ticket
      - POSTGRES_DB=air_ticket
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_air_ticket
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./air_ticket/staticfiles:/var/www/html/static
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:1370"
    depends_on:
      - app
    networks:
      - mynetwork

  redis:
    image: redis:7.2.4
    container_name: redis_air_ticket
    volumes:
      - redis-db-volume:/data
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - mynetwork

  celery-worker:
    build: .
    user: ${CURRENT_UID}
    container_name: celery_worker
    env_file:
      - .env.docker
    command: celery -A core worker --loglevel=info
    volumes:
      - ./air_ticket:/air_ticket
    depends_on:
      - app
      - redis
      - celery-beat
    networks:
      - mynetwork

  celery-beat:
    build: .
    user: ${CURRENT_UID}
    container_name: celery_beat
    environment:
      - BROKER_CONNECTION_RETRY_ON_STARTUP=True
    env_file:
      - .env.docker
    command: celery -A core beat --loglevel=info --scheduler redbeat.schedulers.RedBeatScheduler
    volumes:
      - ./air_ticket:/air_ticket
    depends_on:
      - redis
      - app
    networks:
      - mynetwork

  flower:
    build: .
    user: ${CURRENT_UID}
    container_name: flower
    env_file:
      - .env.docker
    command: sh -c "celery -A core flower --address=0.0.0.0 --port=5555"
    volumes:
      - ./air_ticket:/air_ticket
    depends_on:
      - celery-worker
      - celery-beat
      - redis
    ports:
      - "5555:5555"
    networks:
      - mynetwork

networks:
  mynetwork:
    external: True
    name: mynetwork

volumes:
  postgres-db-volume:
  redis-db-volume:
