# Generated by Django 5.0.1 on 2024-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                default=380675235, max_length=11, unique=True
            ),
            preserve_default=False,
        ),
    ]
