# Generated by Django 5.0.1 on 2024-03-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airplane",
            name="places_amount",
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Economy", "economy"),
                            ("Business", "business"),
                            ("First Class", "first Class"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="flight.airplane",
                    ),
                ),
            ],
        ),
    ]
