# Generated by Django 5.0.1 on 2024-03-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="passenger",
            name="passport_id",
            field=models.CharField(max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
