# Generated by Django 5.0.1 on 2024-03-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_order_created_at_order_updated_at"),
        ("customer", "0002_passenger_passport_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passenger",
            name="email",
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.order",
                    ),
                ),
            ],
        ),
    ]
