# Generated by Django 5.0.1 on 2024-03-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_remove_passenger_email_contact"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
    ]
