# Generated by Django 5.0.1 on 2024-03-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_contact_created_at_contact_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="order",
        ),
    ]
