# Generated by Django 5.0.1 on 2024-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_remove_contact_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
