# Generated by Django 5.0.1 on 2024-03-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_preorder"),
        ("flight", "0008_alter_flight_airplane"),
    ]

    operations = [
        migrations.AddField(
            model_name="preorder",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="flight.flight",
            ),
            preserve_default=False,
        ),
    ]
