# Generated by Django 5.0.1 on 2024-03-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_preorder_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="preorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="booking.preorder",
            ),
            preserve_default=False,
        ),
    ]
