# Generated by Django 5.0.1 on 2024-03-04 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_ticket_preorder"),
        ("flight", "0008_alter_flight_airplane"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="preorder",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger_amount", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Preorder", "preorder"),
                            ("Processed", "processed"),
                            ("Completed", "completed"),
                            ("Canceled", "canceled"),
                        ],
                        default="preorder",
                        max_length=20,
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight.flight",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="booking.order",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="PreOrder",
        ),
    ]
