# Generated by Django 5.0.1 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_remove_ticket_preorder_order_ticket_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="luggage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="lunch",
            field=models.BooleanField(default=False),
        ),
    ]
