# Generated by Django 5.0.1 on 2024-03-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_order_created_at_order_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="flight",
        ),
    ]
