# Generated by Django 5.0.1 on 2024-03-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_remove_order_flight"),
        ("customer", "0004_alter_contact_order"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.order"
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
