# Generated by Django 5.0.1 on 2024-03-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0014_remove_ticket_order_ticket_cart"),
        ("customer", "0006_remove_contact_order"),
        ("flight", "0009_alter_seat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.ticketcart",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.passenger",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flight.seat"
            ),
        ),
    ]
