# Generated by Django 5.0 on 2024-04-14 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0018_booking_created_at"),
        ("customer", "0008_alter_contact_phone_number"),
        (
            "flight",
            "0010_remove_seat_airplane_remove_seat_is_available_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.ticketcart",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flight.flight",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="booking.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcart",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer.contact",
            ),
        ),
        migrations.AlterField(
            model_name="ticketcart",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flight.flight",
            ),
        ),
    ]
