# Generated by Django 5.0 on 2024-04-15 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0019_alter_booking_cart_alter_booking_flight_and_more"),
        ("customer", "0008_alter_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="booking.ticketcart"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="passenger",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="customer.passenger"
            ),
        ),
    ]
