# Generated by Django 5.0 on 2024-04-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_alter_ticket_cart_alter_ticket_passenger"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
