# Generated by Django 5.0 on 2024-04-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0021_booking_is_active"),
        ("flight", "0015_flight_booked_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flight.flight",
            ),
            preserve_default=False,
        ),
    ]
