# Generated by Django 5.0 on 2024-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_alter_ticket_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booked_seat_number",
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
