# Generated by Django 5.0.1 on 2024-03-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_remove_contact_order"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.contact",
            ),
            preserve_default=False,
        ),
    ]
