# Generated by Django 5.0 on 2024-04-15 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0020_alter_ticket_cart_alter_ticket_passenger"),
        ("flight", "0011_alter_flight_airplane_alter_flight_arrival_airport_and_more"),
        ("orders", "0005_remove_order_cart_order_flight_orderticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="flight.flight"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="seat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="flight.seat",
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="booking.ticket"
            ),
        ),
    ]
