# Generated by Django 5.0 on 2024-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_alter_order_flight_alter_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderticket",
            name="seat",
        ),
        migrations.AddField(
            model_name="orderticket",
            name="seat_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
