# Generated by Django 5.0 on 2024-04-18 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0023_alter_ticket_flight"),
        (
            "flight",
            "0018_alter_flight_airplane_alter_flight_arrival_airport_and_more",
        ),
        ("orders", "0007_remove_orderticket_seat_orderticket_seat_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="flight.flight",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderticket",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="booking.ticket",
            ),
        ),
    ]
