# Generated by Django 5.0.1 on 2024-03-01 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airplane",
            name="places_amount",
        ),
    ]
