# Generated by Django 5.0.1 on 2024-03-02 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_remove_airplane_places_amount_seat"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("airport", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
                ("iata", models.CharField(max_length=255)),
                ("icao", models.CharField(max_length=255)),
                (
                    "terminal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gate",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scheduled", models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name="flight",
            name="departure_airport",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="departure_date",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="destination_airport",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="destination_date",
        ),
        migrations.AddField(
            model_name="flight",
            name="iata",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="icao",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="number",
            field=models.CharField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arriving_flight",
                to="flight.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_flight",
                to="flight.place",
            ),
            preserve_default=False,
        ),
    ]
