# Generated by Django 5.0.1 on 2024-03-03 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_remove_flight_created_at_remove_flight_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
                ("iata", models.CharField(max_length=255)),
                ("icao", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="flight",
            name="departure",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="arrival",
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_scheduled",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_scheduled",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrival_flight",
                to="flight.airport",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_flight",
                to="flight.airport",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Place",
        ),
    ]
