# Generated by Django 5.0.1 on 2024-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0008_alter_flight_airplane"),
    ]

    operations = []
