# Generated by Django 5.0.1 on 2024-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0009_alter_seat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="seats_amount",
            field=models.PositiveIntegerField(default=700),
        ),
    ]
