# Generated by Django 5.0 on 2024-04-15 08:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0011_alter_flight_airplane_alter_flight_arrival_airport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="ordered_seats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="flight",
            name="seats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="flight.airplane"
            ),
        ),
    ]
