# Generated by Django 5.0 on 2024-04-15 08:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0012_flight_ordered_seats_flight_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="ordered_seats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="seats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
