# Generated by Django 5.0 on 2024-04-16 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0014_alter_flight_ordered_seats_alter_flight_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="booked_seats",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
    ]
